wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
agent:
  desc: null
  value: ppo-lagrange
config_name:
  desc: null
  value: standard
cost_gamma:
  desc: null
  value: 0.99
cost_lim:
  desc: null
  value: 25
cpu:
  desc: null
  value: 1
env:
  desc: null
  value: Safexp-PointGoal1-v0
epochs:
  desc: null
  value: 50
exp_name:
  desc: null
  value: ppo_safe
gamma:
  desc: null
  value: 0.99
hid:
  desc: null
  value: 64
l:
  desc: null
  value: 2
penalty_lr:
  desc: null
  value: 0.005
seed:
  desc: null
  value: 0
steps:
  desc: null
  value: 8000
